/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  "header-01": {
    name: "header-01",
    description: "A sidebar in a popover popover of sidebar blocks.",
    type: "registry:block",
    registryDependencies: ["sidebar"],
    files: [
      {
        path: "registry/src/headers/header-01.tsx",
        type: "registry:page",
        target: "app/dashboard/page.tsx",
      },
      {
        path: "registry/ui/button.tsx",
        type: "registry:component",
        target: "components/ui/button.tsx",
      },
      {
        path: "registry/ui/alert.tsx",
        type: "registry:component",
        target: "components/alert.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/alert.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["sidebar", "dashboard"],
    meta: undefined,
  },
};
